name: UpdateForecastingWeeks 

on:

  workflow_dispatch:

  # scheduled run every Friday at 14.00 p.m. (Friday 13.00 p.m. UTC)
  schedule:
    - cron: '00 13 * * 5'

  
    
jobs:

  update_forecasting_weeks_job:
    if: github.repository_owner == 'Predizioni-Epidemiologiche-Italia'
    runs-on: ubuntu-latest
    steps:

    # Checkout the python tools repo
    # -------------------------------------------      
    - name: checkout python tools repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: 'Predizioni-Epidemiologiche-Italia/hub-tools'
        ref: 'main'
        path: './tools/'

    # Checkout the data repository
    # -------------------------------------------      
    - name: checkout data repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: 'Predizioni-Epidemiologiche-Italia/Influcast'
        ref: 'main'
        path: './repo/'


    
    # Run Pyton code
    # -------------------------
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    
    - run: pip install pandas isoweek==1.3.3
    
    - name: Pyhton
      id: update_forecasting_weeks
      run: |
        python ./tools/code/update_forecasting_weeks.py --hub_path ./repo

    - name: Commit data repo changes
      uses: EndBug/add-and-commit@v7
      with: 
          cwd: './repo'
          message: "Update data storage"
          default_author: github_actions
          push: true
